spring:
  application:
    name: coupon-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/coupondb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8084

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://coupon-db:3306/coupondb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: kafka:9092
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080
