spring:
  application:
    name: event-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/eventdb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8083

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://event-db:3306/eventdb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: kafka:9092
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080
member-service:
  base-url: http://member-service:8080
